# Generated by Django 3.0.5 on 2020-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('categoryimage', models.ImageField(upload_to='category_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='medic.Category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='product_categories',
            field=models.ManyToManyField(blank=True, to='medic.ProductCategory'),
        ),
    ]
