# Generated by Django 3.0.5 on 2020-05-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0002_auto_20200502_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_productcategory', to='medic.ProductCategory'),
        ),
    ]
